name: containers
run-name: ${{ github.actor }} is testing out containers 🚀
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        cd src
        make dependencies
    - name: Style
      run: |
        cd src
        make check

    - name: Library
      run: |
        cd src
        make s21_containers.a

    - name: Test
      run: |
        cd src
        make test
        
    - name: Revert commit if failed
      if: failure()
      run: |
        git log
        git reset --hard HEAD~1
        git push origin develop --force
