name: containers
run-name: ${{ github.actor }} is testing out containers 🚀
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        cd src
        make dependencies
    - name: Style
      run: |
        cd src
        make check

    - name: Library
      run: |
        cd src
        make s21_containers.a

    - name: Test
      run: |
        cd src
        make test
